### ISSUE TITLE
can't connect to server !

### ISSUE THREAD

**Issue by linxd** [hisptz/hisptz-touch-dashboard#2]
hello, 

   I have built the master branch of  hisptz-touch-dashboard, succeed. but can't connect to server when open the login page.

   It say : please check server address. 
 I have used these address:
   https://play.dhis2.org/2.28 /2.27 /2.26/ and myself's service url . none can connect. 
  I can connect the server with the apk download from google app store.

   why? can you help me?
   Thanks.

**Comment by chingalo** [comment]
Hello linxd,
It is honor to that you really being interested with our mobile apps.

I have updated the read me for the app, you may follow steps.
